### ISSUE TITLE
Hello,I want to find the same research in GED and graph similarity.

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [kazimierz-256/Maximum-common-unlabelled-subgraph-algorithm#2]
Hello, fiend:
My interest is **Graph Edit Distance** in graph similarity search. Recently, I am finding some codes about GED and **want to implement it**. Unfortunately, there are some reasons why I can't implement it. I read a lot of papers related to graph edit distance such as [Similarity Search in Graph Databases: A Multi-layered Indexing Approach](http://www.cs.fsu.edu/~zhao/pzhao4files/icde17.pdf) 、[An Efficient Probabilistic Approach for Graph Similarity Search ](https://arxiv.org/pdf/1706.05476.pdf?forcedefault=true) and other papers which tends to calculate GED. 
Sometimes I am lack of specified knowledge, I cannot understand it fully.  I want to find a community where I can communicate with others but in vain. Could you recommend some tips for me? Hope for your reply.

**Comment by kazimierz-256** [comment]
Please contact me using the [google form](https://docs.google.com/forms/d/e/1FAIpQLSeQhEOrEW1OSsyltJOPwXFw8zXvKw9fbAQb1XmCOycsq9SOlw/viewform?usp=sf_link) so that I can reply to you in private.

**Comment by tiankonghenlan20113046** [comment]
> Please contact me using the [google form](https://docs.google.com/forms/d/e/1FAIpQLSeQhEOrEW1OSsyltJOPwXFw8zXvKw9fbAQb1XmCOycsq9SOlw/viewform?usp=sf_link) so that I can reply to you in private.

Thanks  I have sent your my contact.
